[build]
  base = "/" 
  publish = "/build" 

[build.environment]
  NODE_VERSION = "18" # Specify the Node.js version

[[redirects]]
  from = "/*"
  to = "/public/index.html"
  status = 200
[context.production.environment]
MONGOURI = "mongodb+srv://your-mongodb-uri" 
REACT_APP_API_HOST="http://localhost:5000"
JWT_SECRET="your"